### ISSUE TITLE
Expand fermentable data models

### ISSUE THREAD

**Issue by MichaelWashburnJr** [BrewCenter/BrewCenterAPI#43]
The fermentable model needs refactoring as pointed out by some brewers on reddit. We need to be able to track who makes the fermentable, what year the data is from, as well as some additional values regarding grain and potential sugars. If you know of values that this should have please include them here. 

It might also be nice to have a notion of a 'product line' or something like that, so you can get all the grain from a specific manufacturer and see how it's values changed with each harvest year.

**Comment by MichaelWashburnJr** [comment]
> Your malt model is broken and is based on the homebrewers approach to calculating extract. I should be able to provide information like Extract Dry Basis and Moisture and you calculate the point contributions (ppg, pkgl, etc.) based off that. It can even be computed at the time the model is created since that value isn't really going to change.

**Comment by MichaelWashburnJr** [comment]
Read in depth the [BeerXML](http://www.beerxml.com/) standard and try to mimmick it such that the JSON produced by the API will be effectively BeerJSON, the JSON alternative to BeerXML

**Comment by pricelessbrewing** [comment]
> Your malt model is broken and is based on the homebrewers approach to calculating extract. I should be able to provide information like Extract Dry Basis and Moisture and you calculate the point contributions (ppg, pkgl, etc.) based off that. It can even be computed at the time the model is created since that value isn't really going to change.

It is true that dry extract vs PPG are not strictly equivalent, however they can be reconciled with minimal loss in accuracy (~0.1-0.2%). The math required to do so is pretty straight forward, and handling PPG and wort volume is much easier than handling dry extract, plato, sg, water weight, and converting back and forth 12 times. 

Add parameters

- % Dry Extract
- % Dry Extract (Fine Grind)
- Soluble Protein
- Total Nitrogen
- S/T protein ratio (soluble / total) or Kolbach index
- Kernel size
- Hardness
- Viscosity

After maltster specs are fully described, proof of concept parameters may be added to describe the flavor profile.

**Comment by MichaelWashburnJr** [comment]
@pricelessbrewing what's the % Dry Extract and % Dry Extract (fine grind) attributes you're suggesting adding?

**Comment by pricelessbrewing** [comment]
% dry extract is the percentage of extract (as a ratio to the potential extract of succrose) when 1 lb of the malt is mashed and results in 1 gallon of sugar solution, which will include the grains moisture content. 

It's the *correct* alternative of PPG, and is more precise due to malster spec sheets rounding to the nearest integer on PPG, but nearest half integer or tenth decimal on % Dry extract. As such, when % Dry and PPG are both available, % Dry should be preferred.

% Dry Extract = PPG potential of grain / PPG potential of Succrose, which is usually 46, but sometimes 46.21 is used. 

IE a PPG of 36 = 36/46=78.26%

**Comment by pricelessbrewing** [comment]
% Dry Extract (Fine grind) is typically listed, but not always, on a malster spec sheet. Where % Dry extract, and PPG, are typically calculated using a typical brewery grain crush using a congress mash or ASBC "mash", a the fine grind dry basis % extract uses... a very fine grind and the same mash specs. It's usually 1-3% higher due to the fine grind.

**Comment by MichaelWashburnJr** [comment]
I see. So you think it's best to list % Dry Extract, % Dry Extract Fine Grind, and PPG separate from eachother, as opposed to using just one of them in a "Yield" attribute (which is what the beer xml spec does)

**Comment by MichaelWashburnJr** [comment]
@pricelessbrewing I've been working on a domain model to show the fermentables in the database, Can you to take a look and see what you think? I've also added in the concept of different fermentables and tracking the types of sugars that compose a fermentable. [Link to google drive](https://www.draw.io/?state=%7B%22folderId%22:%220BwEjRillyZroZ2JpRVdlSXlSSVU%22,%22action%22:%22create%22,%22userId%22:%22116038274590759263782%22%7D#G0BwEjRillyZroWlhmWWtnNFU1bHc)

**Comment by MichaelWashburnJr** [comment]
Latest diagram of how the fermentable model should look: ![fermentable domain model 1](https://user-images.githubusercontent.com/4491428/31078927-017a872e-a752-11e7-8ee2-291d8de61b2e.jpg)
